// Generated by CoffeeScript 1.4.0
(function() {

  Ext.Loader.setConfig({
    enabled: true
  });

  Ext.application({
    autoCreateViewport: true,
    name: "App",
    launch: function() {
      return window.Application = this;
    }
  });

  Ext.onReady(function() {
    return Deft.Injector.configure({
      noteStore: 'App.mock.store.NoteStore',
      noteListStore: 'App.mock.store.NoteListStore',
      messageBus: {
        value: {
          noteSelected: function() {
            return console.log('note selected!');
          }
        }
      }
    });
  });

}).call(this);
