// Generated by CoffeeScript 1.4.0
(function() {

  describe("Ext JS", function() {
    it("has loaded", function() {
      return expect(Ext).toBeDefined();
    });
    it("has a version", function() {
      return expect(Ext.getVersion()).toBeTruthy();
    });
    return it("has version number 4.x", function() {
      return expect(Ext.getVersion().major).toEqual(4);
    });
  });

  describe("During initialization and setup, the application", function() {
    it("has loaded Application with expected Application name", function() {
      expect(window.Application).toBeDefined();
      return expect(window.Application.name).toEqual("App");
    });
    return it("has created DeftJS IoC items", function() {
      expect(Deft.ioc.Injector.canResolve("noteStore")).toBeTruthy();
      return expect(Deft.ioc.Injector.canResolve("some$Unknown$Alias")).toBeFalsy();
    });
  });

}).call(this);
